// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7d7ByjIWOEI-sxcTe0WT_a9lTBBfVTBk',
    appId: '1:869967337150:web:beebf82d39ba4cb24bb0ef',
    messagingSenderId: '869967337150',
    projectId: 'flutter-firebase-crud-7bd52',
    authDomain: 'flutter-firebase-crud-7bd52.firebaseapp.com',
    storageBucket: 'flutter-firebase-crud-7bd52.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGGMZ4SBrnvkyTd4DiM5lEkpGEYCx1UDY',
    appId: '1:869967337150:android:8fee3a12ef5bb5274bb0ef',
    messagingSenderId: '869967337150',
    projectId: 'flutter-firebase-crud-7bd52',
    storageBucket: 'flutter-firebase-crud-7bd52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt2XiTuU-qv5tGoLdJKc47DiSaPddqgjU',
    appId: '1:869967337150:ios:8ca6c490505b92fb4bb0ef',
    messagingSenderId: '869967337150',
    projectId: 'flutter-firebase-crud-7bd52',
    storageBucket: 'flutter-firebase-crud-7bd52.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt2XiTuU-qv5tGoLdJKc47DiSaPddqgjU',
    appId: '1:869967337150:ios:1457529c57a43f7e4bb0ef',
    messagingSenderId: '869967337150',
    projectId: 'flutter-firebase-crud-7bd52',
    storageBucket: 'flutter-firebase-crud-7bd52.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseCrud.RunnerTests',
  );
}
